In [17]:
import deepchem as dc 

smiles = ['CC(C)Nc1ccnc(N2CCN(Cc3cccs3)C(CCO)C2)n1', 'COc1cc(=O)n(-c2ccccc2)cc1C(=O)N1CCC2(CC1)OCCO2','O=C(c1nc2ncccn2n1)N1CCCn2cc(-c3ccccc3)nc21']

In [3]:
featurizer = dc.feat.CircularFingerprint()
features = featurizer(smiles)

features, type(features), features.shape

(array([[0., 1., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 numpy.ndarray,
 (3, 2048))

In [44]:
# atomic feature return

featurizer = dc.feat.BPSymmetryFunctionInput(max_atoms=150)
features = featurizer('CCCC(=O)OC[C@@H](OC(=O)CCC)[C@@H](OC(=O)CCC)[C@H](Cn1c2nc(=O)[nH]c(=O)c-2nc2cc(C)c(C)cc21)OC(=O)CCC')

print(features.shape)
features[0].shape # a

(1, 150, 4)


(150, 4)

In [30]:
import pandas as pd 

df = pd.read_csv('/root/Competitions/DACON/4. JUMP AI 2023/data/rdkit_train.csv')

df.head()
df.iloc[:, 1:]

1          2         3         4         5        6        7  \
0     12.482330  12.482330  0.218070 -0.218070  0.598984  400.504  376.312   
1     12.098337  12.098337  0.035440 -0.035440  0.924896  301.415  282.263   
2      4.646025   4.646025  0.712008  0.712008  0.723816  297.366  278.214   
3     13.641142  13.641142  0.285211 -3.644786  0.535042  494.665  460.393   
4     12.661906  12.661906  0.017599 -0.019074  0.798359  268.316  252.188   
...         ...        ...       ...       ...       ...      ...      ...   
3493  13.033764  13.033764  0.021641 -4.519462  0.864779  396.200  382.088   
3494  12.917253  12.917253  0.136950 -0.502147  0.608883  359.389  342.253   
3495  11.269030  11.269030  0.147677 -0.147677  0.660200  261.325  242.173   
3496  11.686457  11.686457  0.143751 -0.539601  0.664083  284.699  271.595   
3497   5.201697   5.201697  0.871427  0.871427  0.694659  295.407  278.271   

               8      9        10  ...  182  183  184  185  186  187  188  \
0     400.156912  148.0  0.269078  ...  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
1     301.124883  110.0  0.228549  ...  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
2     297.170194  114.0  0.207414  ...  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
3     494.246395  186.0  0.246345  ...  0.0  0.0  0.0  1.0  0.0  0.0  0.0   
4     268.121178  102.0  0.258122  ...  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
...          ...    ...       ...  ...  ...  ...  ...  ...  ...  ...  ...   
3493  395.052750  136.0  0.434948  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3494  359.138225  134.0  0.299584  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3495  261.147727  102.0  0.305281  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3496  284.056385  102.0  0.339278  ...  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
3497  295.103085  106.0  0.118403  ...  0.0  0.0  0.0  0.0  0.0  0.0  1.0   

      189  190  191  
0     0.0  0.0  0.0  
1     0.0  0.0  0.0  
2     0.0  0.0  0.0  
3     0.0  0.0  0.0  
4     0.0  0.0  0.0  
...   ...  ...  ...  
3493  0.0  0.0  0.0  
3494  0.0  0.0  0.0  
3495  0.0  0.0  0.0  
3496  0.0  0.0  0.0  
3497  0.0  0.0  0.0  

[3498 rows x 191 columns]

In [26]:
featurizer = dc.feat.Mol2VecFingerprint(radius=2)
features = featurizer(smiles[0])

mol2vec = [] 
mol2vec.append(features)
mol2vec.append(features)
mol2vec.append(features)
# for f in features:
#     print(f.shape)
#     mol2vec.append(f)
    
import numpy as np

features = np.concatenate(mol2vec, axis=0)
print(features.shape)
# features[0] # a

(3, 300)


In [14]:
# 내가 했던거 거의 대부분 포함됨 
featurizer = dc.feat.MolGraphConvFeaturizer(use_edges=True, use_chirality=True, use_partial_charge=True)
features = featurizer(smiles)

print(features.shape)
print(features[0]) # a
# features[0].node_featuresfeatures[0]
features[0].node_features

(3,)
GraphData(node_features=[25, 33], edge_index=[2, 54], edge_features=[54, 11], pos=[0])


array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         0.        ,  0.        , -0.04507493],
       [ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.04461221],
       [ 1.        ,  0.    

In [60]:
# 내가 했던거 거의 대부분 포함됨 
featurizer = dc.feat.PagtnMolGraphFeaturizer(max_length=5)
features = featurizer(smiles)

print(features.shape)
print(features[0]) # a
# features[0].node_features

(3,)
GraphData(node_features=[25, 94], edge_index=[2, 625], edge_features=[625, 42])


In [35]:
from rdkit.Chem import MolFromSmiles
featurizer = dc.feat.MolGanFeaturizer(max_atom_count=30)

rdkit_mol = MolFromSmiles(smiles[0])
features = featurizer([rdkit_mol, smiles[0]])

print(features.shape)
print(features[0])

Failed to featurize datapoint 0, CC(C)Nc1ccnc(N2CCN(Cc3cccs3)C(CCO)C2)n1. Appending empty array
Exception message: 16
Failed to featurize datapoint 1, CC(C)Nc1ccnc(N2CCN(Cc3cccs3)C(CCO)C2)n1. Appending empty array
Exception message: 16


(2, 0)
[]


In [40]:
featurizer = dc.feat.OneHotFeaturizer()

features = featurizer(smiles)

print(features.shape)
print(features[0]) # a

(3, 100, 35)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [43]:
featurizer = dc.feat.PubChemFingerprint()

features = featurizer(smiles)

print(features.shape)
print(features[0]) # a

(3, 881)
[1 1 1 0 0 0 0 0 0 1 1 1 1 0 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0
 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 1 0 0
 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
 0 0 0 0 0 1 0 1 0 0 0 1 1 1 0 0 1 0 1 1 1 0 1 0 0 1 0 0 0 0 0 0 1 1 0 1 0
 1 1 1 1 1 1 1 0 1 1 0 0 0 1 1 0 0 1 0 1 1 1 1 1 0 0 1 0 0 0 0 0 0 1 0 0 1
 0 0 0 0 0 1 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 1 1 0
 0 1 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 1
 0 1 0 1 0 0 1 0

In [53]:
# molecluar feature, normalization 안됨
featurizer = dc.feat.RDKitDescriptors()

features = featurizer(smiles)

print(features.shape)
print(features[0]) # a

(3, 209)
[ 9.47860857e+00  9.47860857e+00  2.03619985e-01  2.03619985e-01
  7.89665676e-01  3.61515000e+02  3.34299000e+02  3.61193631e+02
  1.36000000e+02  0.00000000e+00  2.26852645e-01 -3.96313446e-01
  3.96313446e-01  2.26852645e-01  1.36000000e+00  2.24000000e+00
  2.96000000e+00  3.21334738e+01  1.00938656e+01  2.27838240e+00
 -2.40883900e+00  2.21651680e+00 -2.53046023e+00  7.09426307e+00
  1.35726547e-01  3.09258553e+00  1.68380626e+00  6.48675799e+02
  1.76480536e+01  1.49284088e+01  1.57449054e+01  1.21521983e+01
  8.87256612e+00  9.75221893e+00  6.70287955e+00  7.73512474e+00
  4.36827796e+00  5.22942720e+00  3.18520418e+00  3.91462462e+00
 -1.70000000e+00  3.09258553e+00  1.81019185e+01  8.59955206e+00
  4.90141128e+00  1.53075510e+02  1.53232257e+01  5.81786278e+00
  0.00000000e+00  5.94833928e+00  0.00000000e+00  0.00000000e+00
  4.89990973e+00  4.98397852e+00  4.98397852e+00  1.13367859e+01
  6.06636707e+00  3.77810929e+01  5.59435800e+01  0.00000000e+00
  5.10652739e+00

In [58]:
# molecluar feature, normalization 안됨
featurizer = dc.feat.MATFeaturizer()

features = featurizer(smiles)

print(features.shape)
print(features[0].node_features.shape) # a
print(features[0].adjacency_matrix.shape) # a
print(features[0].distance_matrix.shape) # a
# node_features
# adjacency_matrix
# distance_matrix


(3,)
(26, 36)
(26, 26)
(26, 26)


In [36]:
# molecluar feature, normalization 안됨
featurizer = dc.feat.DMPNNFeaturizer()

features = featurizer(smiles)

print(features.shape) 
print(features[0]) # a
print(features[0].node_features.shape)
# node_features
# adjacency_matrix
# distance_matrix


(3,)
GraphData(node_features=[25, 133], edge_index=[2, 54], edge_features=[54, 14], global_features=[0])
(25, 133)


In [11]:
import pandas as pd
pd.DataFrame(features[0].node_features).to_csv('node_feature_sample.csv')

In [ ]:
from deepchem.models.torch_models import MPNNModel