In [4]:
from monai.metrics import DiceMetric, ConfusionMatrixMetric
import torch

In [53]:
confusion_M = ConfusionMatrixMetric(metric_name=['fpr','fnr'], compute_sample=False)

In [54]:
sample1 = torch.tensor([0., 0., 0., 1., 1.,]).view(-1,1)
label1 = torch.tensor([0., 0., 1., 1., 0.,]).view(-1,1)

y_pred = torch.tensor([0, 0, 1, 1, 0, 1]).view(-1,1)
y_true = torch.tensor([1, 0, 1, 1, 0, 1]).view(-1,1)

both1 = torch.tensor([0., 0., 0., 1., 1.,0, 0, 1, 1, 0, 1]).view(-1,1)
both1p = torch.tensor([0., 0., 1., 1., 0.,1, 0, 1, 1, 0, 1]).view(-1,1)

print(confusion_M(sample1, label1)) # tp fp tn fn 
print(confusion_M(y_pred, y_true))
# print(confusion_M(both1, both1p)) # [tensor([0.6667]), tensor([0.2000]), tensor([0.8000]), tensor([0.3333])]
print(confusion_M.aggregate()) # 'tpr', 'fpr', 'tnr', 'fnr'
confusion_M.reset()
# sample 1 with label 1 
# tp = 1 -- idx 3
# fp = 1 -- idx 4
# tn = 2 -- idx 0,1
# fn = 1 -- idx 2 
# tpr = tp / tp + fn = 1 / 1+1 = 0.5
# fpr = fp / fp + tn = 1 / 1+2 = 0.33333
# tnr = tn / tn + fp = 2 / 2+1 = 0.66666
# fnr = fn / fn + tp = 1 / 1+1 = 0.5 
# tensor([[[0., 0., 1., 0.]],

#         [[0., 0., 1., 0.]],

#         [[0., 0., 0., 1.]],

#         [[1., 0., 0., 0.]],

#         [[0., 1., 0., 0.]]])
# [tensor([0.5000]), tensor([0.3333]), tensor([0.6667]), tensor([0.5000])]

# y_pred with y_true
# tp = 3 -- idx 2,3,5
# fp = 0 -- None
# tn = 2 -- idx 1,4
# fn = 1 -- idx 0 
# tpr = tp / tp + fn = 3 / 3+1 = 0.75
# fpr = fp / fp + tn = 0 / 0+2 = 0
# tnr = tn / tn + fp = 2 / 2+0 = 1
# fnr = fn / fn + tp = 1 / 1+3 = 0.25

tensor([[[0., 0., 1., 0.]],

        [[0., 0., 1., 0.]],

        [[0., 0., 0., 1.]],

        [[1., 0., 0., 0.]],

        [[0., 1., 0., 0.]],

        [[0., 0., 0., 1.]],

        [[0., 0., 1., 0.]],

        [[1., 0., 0., 0.]],

        [[1., 0., 0., 0.]],

        [[0., 0., 1., 0.]],

        [[1., 0., 0., 0.]]])
[tensor([0.2000]), tensor([0.3333])]


In [66]:
y_pred = torch.tensor([[0,0,0],
                       [0,1,1],
                       [0,1,0]]).view(1, 3, 3)
y = torch.tensor([[0,0,0],
                       [0,1,1],
                       [0,1,1]]).view(1, 3, 3)

n_len = len(y_pred.shape)
reduce_axis = list(range(2, n_len))
intersection = torch.sum(y * y_pred, dim=reduce_axis)

y_o = torch.sum(y, reduce_axis)
y_pred_o = torch.sum(y_pred, dim=reduce_axis)
denominator = y_o + y_pred_o

dice_m = DiceMetric(include_background=True)
print(intersection)
print(denominator)
print(dice_m(y_pred, y)) # dice per axis
# print(dice_m(y_pred, y_true))
# print(dice_m(both1, both1p)) # [tensor([0.6667]), tensor([0.2000]), tensor([0.8000]), tensor([0.3333])]
print(dice_m.aggregate()) # sum--
dice_m.reset()

tensor([[0, 2, 1]])
tensor([[0, 4, 3]])
tensor([[   nan, 1.0000, 0.6667]])
tensor([0.8333])


In [26]:
from sklearn.metrics import confusion_matrix

tn, fp, fn, tp = confusion_matrix(label1, sample1, normalize='true').ravel()
tn, fp, fn, tp = confusion_matrix(y_true, y_pred, normalize='true').ravel()
tn, fp, fn, tp

(1.0, 0.0, 0.25, 0.75)